# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine as builder
WORKDIR /app
# install dependencies without running prepare scripts
COPY package.json package-lock.json* tsconfig.json ./
RUN npm install --ignore-scripts
# copy source
COPY src ./src
# build
RUN npm run build

FROM node:lts-alpine as runner
WORKDIR /app
# copy build and relevant files
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules
# copy other essentials
COPY README.md LICENSE .env.example ./
# set default env
ENV NODE_ENV=production

# default to STDIo mode
ENV SERVER_MODE=stdio

EXPOSE 3000
ENTRYPOINT ["node", "build/cli.js"]
